load("C:\\Users\\zil20\\Desktop\\Machine Learning 2\\wk5\\Homework 5\\djia_data.RData")
load("C:\\Users\\zil20\\Desktop\\Machine Learning 2\\wk5\\Homework 5\\djia_info.RData")
source("C:\\Users\\zil20\\Desktop\\Github Repos\\MSCFMachineLearning2\\hw5\\djia_helpers.R")
#Part (a)
dLogRet=diff(log(as.matrix(djia_close[,1:30])))
ts.plot(as.ts(dLogRet), gpars=list(col=rainbow(30)), main="Daily Log Returns of DJIA Stocks", ylab="Daily Log Return")
#Part (b)
complete_tree=hclust(dist(t(dLogRet)), method="complete")
plot(complete_tree)
complete_cut=cutree(complete_tree, h=0.3)
complete_class=resolve_groups(complete_cut, djia_info)
complete_class$symbol
#Part (c)
complete_cut2=cutree(complete_tree, k=3)
complete_class2=resolve_groups(complete_cut2, djia_info)
unique(complete_class2$industry[[1]])
unique(complete_class2$industry[[2]])
unique(complete_class2$industry[[3]])
#Part (d)
single_tree=hclust(dist(t(dLogRet)), method="single")
plot(single_tree)
#Part (e)
complete_cor_tree=hclust(as.dist(1-cor(dLogRet)), method="complete")
plot(complete_cor_tree)
complete_cor_cut=cutree(complete_cor_tree, k=4)
complete_cor_class=resolve_groups(complete_cor_cut, djia_info)
complete_cor_class$symbol
unique(complete_cor_class$industry[[1]])
unique(complete_cor_class$industry[[2]])
unique(complete_cor_class$industry[[3]])
unique(complete_cor_class$industry[[4]])
#Part (f)
complete_cor_tree2=hclust(as.dist(1-cor(dLogRet, method="spearman")), method="complete")
plot(complete_cor_tree2)
complete_cor_cut2=cutree(complete_cor_tree2, k=4)
complete_cor_class2=resolve_groups(complete_cor_cut2, djia_info)
complete_cor_class2$symbol
unique(complete_cor_class2$industry[[1]])
unique(complete_cor_class2$industry[[2]])
unique(complete_cor_class2$industry[[3]])
unique(complete_cor_class2$industry[[4]])
#Optional 
test_vec=rnorm(100)
test_vec_square=rnorm(100)^2
cor(test_vec, test_vec_square, method="spearman")

head()

summary(complete_cut)
class(cut)
diff()
dim()

