load("C:\\Users\\zil20\\Desktop\\Machine Learning 2\\wk5\\Homework 5\\hw5hierdata.RData")
#Part (a)
plot(hdata, main="The Data Set")
average_tree=hclust(dist(hdata), method="average")
plot(average_tree)
#Part (c)
k=7
average_cut=cutree(average_tree, k=k)
par(mfrow=c(1,2))
plot(hdata, col=average_cut, main="7 Clusters")
plot(average_tree)
abline(h=mean(rev(average_tree$height)[(k-1):k]))
#Part (d)
single_tree=hclust(dist(hdata), method="single")
par(mfrow=c(1,1))
plot(single_tree)
k=7
single_cut=cutree(single_tree, k=k)
plot(hdata, col=single_cut, main="7 Clusters")