load("C:\\Users\\zil20\\Desktop\\Machine Learning 2\\wk5\\Homework 5\\hw5single.RData")
#Part (a)
plot(points, col=pieces)
#Part (b)
kout=kmeans(as.matrix(points), centers=2, algorithm="Lloyd")
plot(points, col=kout$cluster)
#Part (c)
complete_tree=hclust(dist(points), method="complete")
complete_cut=cutree(complete_tree, k=2)
average_tree=hclust(dist(points), method="average")
average_cut=cutree(average_tree, k=2)
par(mfrow=c(2,2))
plot(complete_tree)
plot(points, col=complete_cut, main="Complete method clustering")
plot(average_tree)
plot(points, col=average_cut, main="Average method clustering")
#Part (d)
single_tree=hclust(dist(points), method="single")
single_cut=cutree(single_tree, k=2)
par(mfrow=c(1,2))
plot(single_tree)
plot(points, col=single_cut)