load("C:\\Users\\zil20\\Desktop\\Machine Learning 2\\wk5\\Homework 5\\zip.014.RData")
source("C:\\Users\\zil20\\Desktop\\Machine Learning 2\\wk5\\Homework 5\\plot.digit.R")
#Part (a)
tree=hclust(tangentDist, method="complete")
plot(tree)
cut1=cutree(tree, k=3)
table(y.014.tr, cut1)
cut2=cutree(tree, k=6)
table(y.014.tr, cut2)
#Part (b) changing the method to "average"
#Part (c)
load("C:\\Users\\zil20\\Desktop\\Machine Learning 2\\wk5\\Homework 5\\tangent_distances.RData")
# Change the code in part (a) to use the tangent distance
#Part (d)
install.packages("protoclust")
library(protoclust)
tree1=protoclust(tangentDist)
plot(tree1)
cut=protoclust::protocut(tree1, k=3)
table(y.014.tr, cut$cl)
cutt=protoclust::protocut(tree1, k=6)
table(y.014.tr, cutt$cl)
#Part (e)
par(mfrow=c(2,3))
plot.digit(colMeans(x.014.tr[which(cut2==3),]))
plot.digit(colMeans(x.014.tr[which(cut2==2),]))
plot.digit(colMeans(x.014.tr[which(cut2==1),]))
plot.digit(colMeans(x.014.tr[which(cutt$cl==3),]))
plot.digit(colMeans(x.014.tr[which(cutt$cl==2),]))
plot.digit(colMeans(x.014.tr[which(cutt$cl==1),]))
par(mfrow=c(1,3))
plot.digit(x.014.tr[cutt$protos[3],])
plot.digit(x.014.tr[cutt$protos[2],])
plot.digit(x.014.tr[cutt$protos[1],])
